steps:
# ==========================
# Build Backend
# ==========================
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - "-t"
    - us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-backend:$SHORT_SHA
    - ./backend

# ==========================
# Push Backend
# ==========================
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-backend:$SHORT_SHA

# ==========================
# Build Frontend
# ==========================
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - "-t"
    - us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-frontend:$SHORT_SHA
    - ./frontend

# ==========================
# Push Frontend
# ==========================
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-frontend:$SHORT_SHA

# ==========================
# Deploy
# ==========================
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  args:
    - -c
    - |
      set -e

      gcloud container clusters get-credentials ${_CLUSTER_NAME} \
        --zone ${_CLUSTER_ZONE} \
        --project $PROJECT_ID

      if ! kubectl get deployment cert-manager -n cert-manager &>/dev/null; then
        echo "Installing cert-manager..."

        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml

        kubectl wait \
          --namespace cert-manager \
          --for=condition=Available deployment/cert-manager \
          --timeout=300s

        kubectl apply -f k8s/cert-issuer.yaml
      fi

      kubectl get clusterissuer letsencrypt-prod || kubectl apply -f k8s/cert-issuer.yaml

      export PROJECT_ID=$PROJECT_ID
      export IMAGE_TAG=$SHORT_SHA

      envsubst < k8s/backend-deployment.yaml | kubectl apply -f -

      envsubst < k8s/frontend-deployment.yaml | kubectl apply -f -

      kubectl apply -f k8s/backend-service.yaml
      kubectl apply -f k8s/frontend-service.yaml
      kubectl apply -f k8s/ingress.yaml

      kubectl rollout status deployment/sleepvia-backend
      kubectl rollout status deployment/sleepvia-frontend

substitutions:
  _CLUSTER_NAME: sleepvia-cluster
  _CLUSTER_ZONE: us-west1-a

timeout: 1200s
