steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-backend:$SHORT_SHA', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-backend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-frontend:$SHORT_SHA', './frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/sleepvia-repo/sleepvia-frontend:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - -lc
      - |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID
        kubectl get clusterissuer letsencrypt-prod || kubectl apply -f k8s/cert-issuer.yaml
        PROJECT_ID=$PROJECT_ID envsubst < k8s/backend-deployment.yaml | kubectl apply -f -
        PROJECT_ID=$PROJECT_ID envsubst < k8s/frontend-deployment.yaml | kubectl apply -f -
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/ingress.yaml

substitutions:
  _CLUSTER_NAME: "sleepvia-cluster"
  _CLUSTER_ZONE: "us-west1-a"
options:
  substitutions: true
timeout: 1200s
