apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepvia-frontend
  labels:
    app: sleepvia-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleepvia-frontend
  template:
    metadata:
      labels:
        app: sleepvia-frontend
    spec:
      containers:
        - name: frontend
          image: us-west1-docker.pkg.dev/${PROJECT_ID}/sleepvia-repo/sleepvia-frontend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
