apiVersion: v1
kind: Service
metadata:
  name: sleepvia-frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: sleepvia-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
