apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sleepvia-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: sleepvia-static-ip
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-http01-edit-in-place: "true"
    kubernetes.io/ingress.allow-http: "true"
    ingress.gcp.kubernetes.io/force-https: "false"
spec:
  ingressClassName: gce
  tls:
  - hosts:
    - sleepvia.duckdns.org
    secretName: sleepvia-tls-cert
  rules:
    - host: sleepvia.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sleepvia-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sleepvia-frontend
                port:
                  number: 80
